#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jan 30 10:43:57 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}